export enum AvailabilityStatus {
  AVAILABLE = "AVAILABLE",
  BUSY = "BUSY",
  DEACTIVATED = "DEACTIVATED",
  OFFLINE = "OFFLINE",
  PENDING = "PENDING",
  SUSPENDED = "SUSPENDED",
  UNAVAILABLE = "UNAVAILABLE",
}

export enum CapabilityClass {
  BICYCLE_RIDER = "BICYCLE_RIDER",
  LIGHT_MOTOR_RIDER = "LIGHT_MOTOR_RIDER",
  VEHICLE_DRIVER = "VEHICLE_DRIVER",
}

export enum CertificationType {
  DEFENSIVE_DRIVING = "DEFENSIVE_DRIVING",
  FIRST_AID = "FIRST_AID",
  GOOD_CONDUCT_CERTIFICATE = "GOOD_CONDUCT_CERTIFICATE",
  NTSA_DRIVING_LICENSE_CLASS_BCE = "NTSA_DRIVING_LICENSE_CLASS_BCE",
  NTSA_DRIVING_LICENSE_CLASS_G = "NTSA_DRIVING_LICENSE_CLASS_G",
}

export enum DocumentStatus {
  ACTIVE = "ACTIVE",
  EXPIRED = "EXPIRED",
  PENDING = "PENDING",
  REPLACED = "REPLACED",
  UPLOADED = "UPLOADED",
}

export enum DocumentType {
  DEFENSIVE_DRIVING_CERTIFICATE_COPY = "DEFENSIVE_DRIVING_CERTIFICATE_COPY",
  FIRST_AID_CERTIFICATE_COPY = "FIRST_AID_CERTIFICATE_COPY",
  GOOD_CONDUCT_CERTIFICATE_COPY = "GOOD_CONDUCT_CERTIFICATE_COPY",
  MOTORCYCLE_LICENSE_COPY = "MOTORCYCLE_LICENSE_COPY",
  NATIONAL_ID_BACK = "NATIONAL_ID_BACK",
  NATIONAL_ID_FRONT = "NATIONAL_ID_FRONT",
  VEHICLE_LICENSE_COPY = "VEHICLE_LICENSE_COPY",
}

export enum LocationSource {
  ITRACK_DEVICE = "ITRACK_DEVICE",
  MOBILE_BROWSER = "MOBILE_BROWSER",
  WEB_BROWSER = "WEB_BROWSER",
}

export enum NationalIdType {
  NATIONAL_ID = "NATIONAL_ID",
  PASSPORT = "PASSPORT",
}

export enum PaymentMethodType {
  MPESA_PAYBILL = "MPESA_PAYBILL",
  MPESA_PERSONAL = "MPESA_PERSONAL",
  MPESA_TILL = "MPESA_TILL",
}
