export enum ContactStatus {
  FAILED = "FAILED",
  RESOLVED = "RESOLVED",
  UNRESOLVED = "UNRESOLVED",
}

export enum DocumentType {
  PARCELS_MANIFEST = "PARCELS_MANIFEST",
}

export enum DraftStatus {
  CANCELLED = "CANCELLED",
  CONFIRMED = "CONFIRMED",
  CREATED = "CREATED",
  EXPIRED = "EXPIRED",
}

export enum IncidentType {
  ACCIDENT = "ACCIDENT",
  AGENT_DISAPPEARED = "AGENT_DISAPPEARED",
  GOODS_DAMAGED = "GOODS_DAMAGED",
  GOODS_LOST = "GOODS_LOST",
  THEFT = "THEFT",
}

export enum OrderStatus {
  AGENT_UNRESPONSIVE = "AGENT_UNRESPONSIVE",
  ASSIGNED = "ASSIGNED",
  BROADCASTING = "BROADCASTING",
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED",
  DELAYED = "DELAYED",
  DELIVERED = "DELIVERED",
  ESCALATED = "ESCALATED",
  IN_TRANSIT = "IN_TRANSIT",
  LOST = "LOST",
  PENDING = "PENDING",
  PENDING_PICKUP = "PENDING_PICKUP",
  READY_FOR_BROADCAST = "READY_FOR_BROADCAST",
  REASSIGNED = "REASSIGNED",
}

export enum OrderType {
  BATCH_ITEM = "BATCH_ITEM",
  EXPLICIT = "EXPLICIT",
  SCHEDULED = "SCHEDULED",
}

export enum OutboxStatus {
  DEAD_LETTER = "DEAD_LETTER",
  FAILED = "FAILED",
  PENDING = "PENDING",
  SENT = "SENT",
}

export enum ReassignmentStatus {
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  PENDING = "PENDING",
}

export enum TipPaymentStatus {
  COMPLETED = "COMPLETED",
  PENDING = "PENDING",
}
