export enum AddressTag {
  BILLING = "BILLING",
  BRANCH_LOCATION = "BRANCH_LOCATION",
  PRIMARY = "PRIMARY",
  SHIPPING = "SHIPPING",
}

export const UserRole = {
  AGENT: "AGENT",
  BRANCH_ADMIN: "BRANCH_ADMIN",
  BRANCH_OPERATOR: "BRANCH_OPERATOR",
  BRANCH_CHECKER: "BRANCH_CHECKER",
  BRANCH_FLEET_MANAGER: "BRANCH_FLEET_MANAGER",
  BRANCH_FLEET_SUPPORT: "BRANCH_FLEET_SUPPORT",
  BRANCH_INVENTORY_MANAGER: "BRANCH_INVENTORY_MANAGER",
  BRANCH_MAKER: "BRANCH_MAKER",
  CUSTOMER: "CUSTOMER",
  ORGANIZATION_ADMIN: "ORGANIZATION_ADMIN",
  ORGANIZATION_CHECKER: "ORGANIZATION_CHECKER",
  ORGANIZATION_FLEET_MANAGER: "ORGANIZATION_FLEET_MANAGER",
  ORGANIZATION_FLEET_SUPPORT: "ORGANIZATION_FLEET_SUPPORT",
  ORGANIZATION_INVENTORY_MANAGER: "ORGANIZATION_INVENTORY_MANAGER",
  ORGANIZATION_MAKER: "ORGANIZATION_MAKER",
  ORGANIZATION_OPERATOR: "ORGANIZATION_OPERATOR",
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
} as const;

export type UserRole = (typeof UserRole)[keyof typeof UserRole];
