export const roleLabels: Record<string, string> = {
  AGENT: "Agent",
  BRANCH_ADMIN: "Branch Admin",
  BRANCH_CHECKER: "Branch Checker",
  BRANCH_FLEET_MANAGER: "Branch Fleet Manager",
  BRANCH_FLEET_SUPPORT: "Branch Fleet Support",
  BRANCH_INVENTORY_MANAGER: "Branch Inventory Manager",
  BRANCH_MAKER: "Branch Maker",
  BRANCH_OPERATOR: "Branch Operator",
  CUSTOMER: "Customer",
  ORGANIZATION_ADMIN: "Organization Admin",
  ORGANIZATION_CHECKER: "Organization Checker",
  ORGANIZATION_FLEET_MANAGER: "Organization Fleet Manager",
  ORGANIZATION_FLEET_SUPPORT: "Organization Fleet Support",
  ORGANIZATION_INVENTORY_MANAGER: "Organization Inventory Manager",
  ORGANIZATION_MAKER: "Organization Maker",
  ORGANIZATION_OPERATOR: "Organization Operator",
  SYSTEM_ADMIN: "System Admin",
};
