export { AddressTag } from "@repo/shared/client";

export enum BranchStatus {
  ACTIVE = "ACTIVE",
  DEACTIVATED = "DEACTIVATED",
  SUSPENDED = "SUSPENDED",
}

export enum ComplianceStatus {
  COMPLIANT = "COMPLIANT",
  NON_COMPLIANT = "NON_COMPLIANT",
  SUSPENDED = "SUSPENDED",
}

export enum DayOfWeek {
  FRIDAY = "FRIDAY",
  MONDAY = "MONDAY",
  SATURDAY = "SATURDAY",
  SUNDAY = "SUNDAY",
  THURSDAY = "THURSDAY",
  TUESDAY = "TUESDAY",
  WEDNESDAY = "WEDNESDAY",
}

export enum DocumentStatus {
  ACTIVE = "ACTIVE",
  EXPIRED = "EXPIRED",
  PENDING = "PENDING",
  REPLACED = "REPLACED",
  UPLOADED = "UPLOADED",
}

export enum DocumentType {
  BUSINESS_REGISTRATION_CERT = "BUSINESS_REGISTRATION_CERT",
  CERTIFICATE_OF_COMPLIANCE = "CERTIFICATE_OF_COMPLIANCE",
  CERTIFICATE_OF_INCORPORATION = "CERTIFICATE_OF_INCORPORATION",
  COUNTY_PERMIT = "COUNTY_PERMIT",
  HEALTH_CERTIFICATE = "HEALTH_CERTIFICATE",
  KRA_PIN_CERT = "KRA_PIN_CERT",
  MEMORANDUM_ARTICLES = "MEMORANDUM_ARTICLES",
  NATIONAL_ID = "NATIONAL_ID",
  PARTNERSHIP_DEED = "PARTNERSHIP_DEED",
}

export enum OrganizationStatus {
  ACTIVE = "ACTIVE",
  APPROVED = "APPROVED",
  DEACTIVATED = "DEACTIVATED",
  PENDING_APPROVAL = "PENDING_APPROVAL",
  REJECTED = "REJECTED",
}

export enum OutboxStatus {
  FAILED = "FAILED",
  PENDING = "PENDING",
  SENT = "SENT",
}

export enum RegistrationType {
  LIMITED_LIABILITY_ENTITY = "LIMITED_LIABILITY_ENTITY",
  PARTNERSHIP = "PARTNERSHIP",
  SOLE_PROPRIETOR = "SOLE_PROPRIETOR",
}
